name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [386, amd64, arm, arm64]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Server Image
      - name: Build Server Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reprox:server-linux-${{ matrix.arch }}
          build-args: |
            GOOS=linux
            GOARCH=${{ matrix.arch }}
          file: ./server.Dockerfile

      # Build Client Image
      - name: Build Server Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/reprox:client-linux-${{ matrix.arch }}
          build-args: |
            GOOS=linux
            GOARCH=${{ matrix.arch }}
          file: ./client.Dockerfile
